apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: giropops-nginx
  name: giropops-nginx
spec:
  containers:
  - image: nginx
    name: giropops-nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
